modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/xhanhh/TeamProjectE-Reborn/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
credits="${mod_credits}"
logoFile="logo.png"
description='''
TeamProjectE-Reborn Mod

ProjectE knowledge and EMC syncing reborn!
With this mod, you will have shared EMC and knowledge with your ProjectE team members!
EMC display support for Xaero's Minimap has also been added.

Forked from TeamProjectE by 6LeoY, maintained by Myxhan(xhanhh)
'''

[[mixins]]
config="${mod_id}.mixins.json"

[modproperties.${mod_id}]
catalogueImageIcon="logo.png"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="projecte"
type="required"
versionRange="[1.0.0,)"
ordering="NONE"
side="BOTH"
